stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  image: golang:1.16
  script:
    - go build -o myapp

test_job:
  stage: test
  image: golang:1.16
  script:
    - go test ./...

deploy_job:
  stage: deploy
  image: alpine
  script:
    - echo "Deploy to production"
  only:
    - master
